# Generated by Django 6.0.6 on 2026-06-27 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('MATCH', 'Match Found'), ('MATCH_CANCELLED', 'Match Cancelled'), ('ROOM_INVITE', 'Room Invite'), ('ROOM_JOINED', 'Room Joined'), ('ROOM_CLOSED', 'Room Closed'), ('HOST_CHANGED', 'Host Changed'), ('PARTICIPANT_JOINED', 'Participant Joined'), ('PARTICIPANT_LEFT', 'Participant Left'), ('RECONNECT_SUCCESS', 'Reconnect Success'), ('RECONNECT_FAILED', 'Reconnect Failed'), ('MEDIA_PERMISSION_REQUIRED', 'Media Permission Required'), ('USER_BLOCKED', 'User Blocked'), ('USER_REPORTED', 'User Reported'), ('SYSTEM_NOTICE', 'System Notice')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
