services:
  - type: web
    name: foudy-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "cd backend && daphne -b 0.0.0.0 -p $PORT --proxy-headers foudy_backend.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@foudy.online"
      - key: FRONTEND_URL
        value: "https://www.foudy.online"
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: "https://www.foudy.online,https://foudy.online,https://foudy-alpha.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://www.foudy.online,https://foudy.online,https://foudy-alpha.vercel.app,https://foudy.onrender.com"
      - key: TURN_URL
        sync: false
      - key: TURN_SECRET
        sync: false

  - type: worker
    name: foudy-celery
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && celery -A foudy_backend worker -l info"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: SECRET_KEY
        sync: false

  - type: worker
    name: foudy-matchmaker
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python manage.py run_matchmaking_engine"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SECRET_KEY
        sync: false
