# Generated by Django 6.0.6 on 2026-06-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='max_participants',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('JOINING', 'Joining'), ('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('LEFT', 'Left'), ('REMOVED', 'Removed'), ('DISCONNECTED', 'Disconnected'), ('RECONNECTING', 'Reconnecting')], default='INVITED', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('FULL', 'Full'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('DESTROYED', 'Destroyed')], default='CREATED', max_length=20),
        ),
    ]
