# Generated by Django 6.0.6 on 2026-06-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_max_participants_roomparticipant_joined_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('WAITING', 'Waiting'), ('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('FULL', 'Full'), ('CLOSING', 'Closing'), ('CLOSED', 'Closed'), ('DESTROYED', 'Destroyed')], db_index=True, default='CREATED', max_length=20),
        ),
    ]
