# Generated by Django 6.0.6 on 2026-06-30 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['status', 'created_at'], name='rooms_room_status_576d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['status', 'room'], name='rooms_roomp_status_6d4067_idx'),
        ),
    ]
