# Generated by Django 6.0.6 on 2026-06-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchqueue',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
