# Generated by Django 6.0.6 on 2026-06-30 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_matchqueue_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matchqueue',
            index=models.Index(fields=['is_active', 'score', 'created_at'], name='matching_ma_is_acti_fb4ed0_idx'),
        ),
    ]
